config/routes.rb
Rails.application.routes.draw do
  match '/payments/payment', to: 'payments#payment', as: 'paymentspayment', via: [:get]
  match '/payments/relay_response', to: 'payments#relay_response', as: 'payments_relay_response', via: [:post]
  match '/payments/receipt', to: 'payments#receipt', as: 'payments_receipt', via: [:get]
  authenticated :user, lambda {|u| u.admin?} do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  resources :payments, except: [:edit, :destroy] do
    get :paypal_success, on: :member
    get :paypal_cancel, on: :member
  end
  get '/notification' => 'payments#twocheckout_notification'
  devise_for :users
  root 'payments#new'
end

app/models/payment.rb
# app/models/payment.rb
class Payment < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  include ActionView::Helpers::TextHelper

  class PaymentError < StandardError;end
  class PaypalPaymentNotFoundError < StandardError;end
  class UnsupportedPricingTier < StandardError;end
  class DoubleChargeError < PaymentError;end
  class NonExistentPaymentError < PaymentError;end
  class DoubleAgreeError < PaymentError;end
  class PaypalTokenRequiredError < PaymentError;end
  class UnsupportedPaymentMethodError < PaymentError;end

  PAYMENT_METHODS = {
    paypal: 'paypal',
    stripe: 'stripe'
  }

  PAYPAL_SUPPORTED_CURRENCIES = %w{
    USD
  }

  attr_accessor :paypal_url

  belongs_to :user

  validates :amount, presence: true, numericality: true
  validates :sessions_count, presence: true
  validates_numericality_of :sessions_count, greater_than: 0, only_integer: true

  before_validation :set_amount

  def self.charged
    where(charged: true)
  end

  def self.most_recent
    order('created_at DESC').first
  end

  def self.new_default(attrs={})
    defaults = {
      sessions_count: 4
    }
    attrs = defaults.merge(attrs)
    obj = new(attrs)
    obj.set_amount
    obj
  end

  def paypal?
    payment_method == PAYMENT_METHODS[:paypal]
  end

  def stripe?
    payment_method == PAYMENT_METHODS[:stripe]
  end


  def request_paypal_url(success_callback_url, cancel_callback_url)
    raise NonExistentPaymentError if new_record?

    response = paypal_express_request.setup(paypal_payment_request,
                                            success_callback_url,
                                            cancel_callback_url,
                                            no_shipping: true)

    self.paypal_url = response.redirect_uri
  end

  def charge
    if paypal?
      charge_paypal
    elsif stripe?
      charge_stripe
    else
      raise UnsupportedPaymentMethodError
    end
  end

  def set_amount
    self.amount = 1.00
  end

  def valid_paypal_payment?
    paypal_token.present? && paypal_payer_id.present?
  end

  def amount_in(currency)
    # if tier = PricingTier.where('? BETWEEN min_sessions AND max_sessions',
    #                            sessions_count).first
    #   (sessions_count * tier.price_per_session(currency)).round(2)
    # else
    #   raise UnsupportedPricingTier
    # end
    1.00
  end

  private
  def set_currency(tier)
    if !tier.priced_in?(currency)
      self.currency = 'USD'
    end

    if stripe?
      self.currency = 'USD'
    elsif paypal? && !self.currency.in?(PAYPAL_SUPPORTED_CURRENCIES)
      self.currency = 'USD'
    end
  end

  def sessions_to_credit
    return if user.blank?
    bonus_sessions_count = user.payments.charged.blank? ? 1 : 0
    user.sessions_count + self.sessions_count + bonus_sessions_count
  end

  def charge_paypal
    if not valid_paypal_payment?
      raise PaypalPaymentNotFoundError
    elsif charged?
      raise DoubleChargeError if charged?
    end

    set_amount
    paypal_express_request.checkout!(paypal_token, paypal_payer_id, paypal_payment_request)

    new_sessions_count = sessions_to_credit
    if self.update_attributes(charged: true) && user.present?
      user.update_attribute(:sessions_count, new_sessions_count)
    else
      charged
    end
  end

  def charge_stripe
    begin
      set_amount
      description = if user
                      "Payment for #{user.email}"
                    elsif gift_scholarship
                      "Gift Scholarship Payment to #{gift_scholarship.to}"
                    end

      charge = Stripe::Charge.create(
        amount: (self.amount_in('USD') * 100).to_i.to_s,
        currency: 'usd',
        card: self.stripe_token,
        description: description
      )

      new_sessions_count = sessions_to_credit
      if self.update_attributes(charged: true, stripe_charge_id: charge.id) && user.present?
        user.update_attribute(:sessions_count, new_sessions_count)
      else
        charged
      end
    rescue Stripe::StripeError
      false
    end
  end


  def paypal_express_request
    @paypal_express_request ||=
      Paypal::Express::Request.new(Paypal::Express::Config.to_h)
  end

  def paypal_payment_request
    set_amount
    sessions_count_text = pluralize(sessions_count, 'Test session')
    amount_text = number_to_currency(amount, locale: :en)
    description = "Paypal Payment #{sessions_count_text}, #{amount_text}"

    Paypal::Payment::Request.new(
      action:        :Sale,
      currency_code: self.currency.to_sym,
      amount:        amount,
      description:   description
    )
  end

  def self.cumulative_receipts(date)
    where('charged=true AND payments.created_at <= ?', date.end_of_day).sum('amount')
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  include ActionView::Helpers::NumberHelper
  include PaymentsHelper

  helper :authorize_net
  protect_from_forgery except: :relay_response

  # GET
  # Displays a payment form.
  def payment
    @amount = 1.00
    @sim_transaction = AuthorizeNet::SIM::Transaction.new(AUTHORIZE_NET_CONFIG['api_login_id'], AUTHORIZE_NET_CONFIG['api_transaction_key'], @amount, relay_url: payments_relay_response_url(only_path: false))
  end

  # POST
  # Returns relay response when Authorize.Net POSTs to us.
  def relay_response
    sim_response = AuthorizeNet::SIM::Response.new(params)
    if sim_response.success?(AUTHORIZE_NET_CONFIG['api_login_id'], AUTHORIZE_NET_CONFIG['merchant_hash_value'])
      render text: sim_response.direct_post_reply(payments_receipt_url(only_path: false), include: true)
    else
      render
    end
  end

  # GET
  # Displays a receipt.
  def receipt
    @auth_code = params[:x_auth_code]
  end

  def index
    @payments = current_user.payments.charged
  end

  def new
    @payment = Payment.new_default(currency: 'USD')
  end

  def create
    @payment          = Payment.new(new_payment_params)
    @payment.currency = 'USD'
    @payment.user     = current_user
    @payment.save!
    redirect_to @payment
  end

  def show
    @payment = current_user.payments.find(params[:id])

    redirect_to new_payment_url if @payment.charged?
  end

  def update
    @payment = current_user.payments.find(params[:id])

    payment_method = params[:payment] && params[:payment][:payment_method]

    if !@payment.charged? && payment_method.present?
      @payment.update_attribute(:payment_method, payment_method)
    end

    if not @payment.charged?
      if @payment.paypal?
        process_paypal_payment
      elsif @payment.stripe?
        process_stripe_payment
      end
    else
      redirect_to new_payment_url
    end
  end

  def paypal_success
    @payment                 = current_user.payments.find(params[:id])
    @payment.paypal_token    = params[:token]
    @payment.paypal_payer_id = params[:PayerID]
    @payment.save!

    redirect_to @payment
  end

  def paypal_cancel
    redirect_to new_payment_url, alert: I18n.t('payments.paypal.payment-cancel')
  end

  def twocheckout_notification
    @notification = Twocheckout::ValidateResponse.notification({sale_id: params['sale_id'], vendor_id: 1817037,
      invoice_id: params['invoice_id'], secret: "tango", md5_hash: params['md5_hash']})
    @payment = Payment.find(params['sale_id'])
    if params['message_type'] == "FRAUD_STATUS_CHANGED"
      begin
        if @notification['code'] == "PASS" and params['fraud_status'] == "pass"
          @payment.charged = true
          render text: 'Fraud Status Passed'
        else
          @payment.charged = false
          render text: 'Fraud Status Failed or MD5 Hash does not match!'
        end
        ensure
        @payment.save
      end
    end
  end


  private
  def new_payment_params
    params.require(:payment).permit(:sessions_count)
  end

  def successful_payment_flash
    {
      notice: I18n.t("payments.#{@payment.payment_method}.payment-succeeded.title"),
      flash: {
        body: I18n.t("payments.#{@payment.payment_method}.payment-succeeded.body",
                     amount: number_to_currency(@payment.amount, unit: symbol_for_currency(@payment.currency)),
                     sessions_count: current_user.reload.sessions_count)
      }
    }
  end

  def process_paypal_payment
    if !@payment.charged? && @payment.paypal_payer_id.blank?
      @payment.request_paypal_url(
        paypal_success_payment_url(@payment),
        paypal_cancel_payment_url(@payment)
      )

      redirect_to @payment.paypal_url
    elsif @payment.valid_paypal_payment?
      @payment.charge
      redirect_to new_payment_url, successful_payment_flash
    else
      redirect_to @payment
    end
  end

  def process_stripe_payment
    @payment.update_column(:stripe_token, params[:stripeToken])

    if !@payment.charged? && @payment.stripe_token.present? && @payment.charge
      redirect_to new_payment_url, successful_payment_flash
    else
      redirect_to @payment, alert: I18n.t('payments.stripe.payment-error')
    end
  end

end

app/helpers/payments_helper.rb
module PaymentsHelper
  def payment_tier_data(currency)
    as_html_data(
      currency: symbol_for_currency(currency),
      low_min: 1,
      low_price: PricingTier.find_by_min_sessions(1).price_in(currency),
    )
  end

  def stripe_script_attrs(payment)
    cost = number_to_currency(payment.amount_in("USD"), locale: :en)
    description = "You will be charged #{cost}"

     as_html_data(
       key: ENV['STRIPE_PUBLISHABLE_KEY'],
       amount: (payment.amount_in("USD")*100).to_i.to_s,
       name: "Test Payments",
       description: description,
       image: image_path('stripe-checkout-icon.png'),
     ).merge(src: "https://checkout.stripe.com/v2/checkout.js",
             class: "stripe-button")
  end

  def prices_in_other_currencies(payment)
    ABCD::ENABLED_CURRENCIES.map do |currency|
      next if payment.currency == currency
      number_to_currency(payment.amount_in(currency), unit: symbol_for_currency(currency))
    end.compact
  end
end

app/views/payments/_form.html.slim
- currency = payment.currency

.content-box-mega
  .bundle-container
    - PricingTier.order(:default_sessions).each do |tier|
      - unit = tier.priced_in?(currency) ? symbol_for_currency(currency) : symbol_for_currency(ABCD::DEFAULT_CURRENCY)
      footer
        = form_for payment do |f|
          = f.hidden_field :sessions_count, value: tier.default_sessions
          button.btn.btn-block.btn-bundle class=(tier.featured? ? "btn-success" : "btn-primary")
            = t("payments.bundles.button-#{tier.type}", sessions_count: tier.default_sessions, amount: number_to_currency(tier.package_cost(currency), unit: unit)).html_safe

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.slim
= render "form", payment: @payment

app/views/payments/payment.erb
<%= form_for :sim_transaction, :url => AuthorizeNet::SIM::Transaction::Gateway::TEST do |f| %>
  <%= sim_fields(@sim_transaction) %>
  <%= label_tag 'x_amount', "Total: #{number_to_currency(@amount)}" %>
  <%= label_tag 'x_card_num', 'Credit Card Number'%>
  <%= text_field_tag 'x_card_num' %>
  <%= label_tag 'x_exp_date', 'Expiration Date (MMYY)'%>
  <%= text_field_tag 'x_exp_date' %>
  <br />
  <%= f.submit 'Purchase'%>
<% end %>

app/views/payments/receipt.erb
Thanks for your purchase! Your authorization code is <%=h @auth_code %>.

app/views/payments/relay_response.erb
Sorry, something went wrong, please try your transaction again.

app/views/payments/show.html.slim
- unit = symbol_for_currency(@payment.currency)
- @params = { 'sid' => '1817037', 'mode' => '2CO','li_0_name' => 'Example Product', 'li_0_price' => '1.00'}
- if @payment.valid_paypal_payment?
  .row-fluid
    .span5
      h1.first-one= t('.title')

    .span6.offset1
      p
        a.paypal-badge href="https://www.paypal.com/webapps/mpp/paypal-popup" title="How PayPal Works" onclick="javascript:window.open('https://www.paypal.com/webapps/mpp/paypal-popup','WIPaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;"
          img width="160" height="55" src="https://www.paypalobjects.com/webstatic/mktg/logo/AM_SbyPP_mc_vs_dc_ae.jpg" border="0" alt="PayPal Acceptance Mark"
      p= t('.sub-title', amount: number_to_currency(@payment.amount, unit: unit)).html_safe
      = form_for @payment do |f|
        = render "shared/errors", object: f.object
        .content-box-mini.last-one
          = f.button class: "btn btn-success" do
            i.icon-ok
            | &nbsp;&nbsp;
            = t('helpers.submit.payment.update')
- else
  .content-box-mega.first-one
    .row-fluid
      .span6.offset1
        h1.first-one Payment
        h4.shopping-cart-header
          .topic-group-badge.mini
            i.icon-shopping-cart
          - cost = number_to_currency(@payment.amount, unit: unit)

      .span3.offset1
        .content-box-mini.first-one
          = form_for @payment do |f|
            = f.hidden_field :payment_method, value: Payment::PAYMENT_METHODS[:paypal]
            button.btn.btn-large.btn-block.btn-payment
              .visuallyhidden= t('payments.show.pay-paypal')
              = image_tag "payments-paypal.png", width: 118, height: 42, class: "paypal-pay-image"
        .content-box-mini
          = form_for @payment, html: { class: 'stripe' } do |f|
            script*stripe_script_attrs(@payment)
            = f.hidden_field :payment_method, value: Payment::PAYMENT_METHODS[:stripe]
            = hidden_field_tag :stripeToken
            / button.btn.btn-large.btn-block.btn-payment
            /   .visuallyhidden= t('payments.show.pay-cards')
            /   = image_tag "payments-cards.png", width: 153, height: 30, class: "cards-pay-image"
        .content-box-mini
          - @form = Twocheckout::Checkout.form(@params, "Pay for your Order with 2checkout")
          = @form.html_safe
        .content-box-mini
          = link_to 'Paywith Authoize.net', paymentspayment_path